working start, stop, restart, accept-eula

diff --git a/minecraft_server b/minecraft_server
--- a/minecraft_server
+++ b/minecraft_server
@@ -12,6 +12,9 @@
 MC_USER=minecraft       # User name running the minecraft server
 MC_PROC=minecraft.jar   # name of minecraft jar file
 MC_DIR=/home/minecraft/server # Directory where the server should run
+MC_JAVA_OPS='-Xmx1G -Xms1G'   # java options for minecraft server
+
+JAVACMD=$(which java)
 
 USAGE=$(cat <<EOF
 Usage:  $0 <option>
@@ -34,6 +37,9 @@ Options:
   status
     Give the status of the server
 
+  accept-eula
+    Accepts Mojangs EULA and set eula.txt correct
+
   send <command>
     Sends a command to the Minecraft server
 
@@ -51,7 +57,7 @@ EOF
 
 getPID() {
   local PID
-  PID=$( ps -f -u $MC_USER | grep $MC_PROC | grep -v grep | awk '{print $2}' )
+  PID=$( ps -f -u $MC_USER | grep "$MC_PROC" | grep -v "sh -c" |  grep -v grep | awk '{print $2}' )
   printf "%d\n" $PID
 }
 
@@ -60,8 +66,11 @@ getPID() {
 #
 
 isRunning() {
-  getPID | grep -q '0'
-  echo $?
+  if [  $(getPID) -eq 0 ] ; then
+	echo 0
+  else
+	echo 1
+  fi
 }
 
 # execute command as minecraft user
@@ -70,10 +79,56 @@ execCMD() {
 	# if running as root, switch to defined user
 
 	if [ $(id -u) -eq 0 ]; then
-		su -s /bin/sh -c "$1" $MC_USER
+		su -s /bin/sh -c "$1" $MC_USER $2
 	else
-		sh -c "$1"
+		sh -c "$1" $2
 	fi
+}
+
+#
+# setProp
+#
+# setProp <filename> <property> <value>
+#
+#
+setProp() {
+
+  grep -q "^$2\s*\=" $1
+
+  if [ $? -ne 0 ] ; then
+	echo "$prop=$val" >> $1
+  else
+    sed -i "/^$2\s*=/ c $2=$3" $1
+  fi
+
+}
+
+#
+# send a command to the running minecraft server
+sendCMD() {
+  echo $1 >> $MC_DIR/input.con
+}
+
+#
+# create eula.txt if it does not exist
+#
+
+createEULA() {
+
+  if [ ! -f $MC_DIR/eula.txt  ] ; then
+       execCMD "echo '#EULA file created by minecraft script\neula=false' > $MC_DIR/eula.txt"
+  fi
+
+}
+
+#
+# EULA accepted (0) or not (1)
+#
+
+acceptEULA() {
+  local OK=1
+  grep eula $MC_DIR/eula.txt |  grep -q 'true' && OK=0
+  echo "$OK"
 }
 
 # 
@@ -102,19 +157,136 @@ checkOK() {
   if [ ! -f $MC_DIR/testfile ] ; then
 	echo "the user $MC_USER has not write access to directory $MC_DIR"
 	exit 1
+  else
+    rm $MC_DIR/testfile
   fi
 
+  # check if EULA accepted
+
+  createEULA
+
+  if [ $(acceptEULA) -eq 1 ] ; then
+	echo "you must accept Mojangs EULA, either set eula=true in $MC_DIR/eula.txt"
+	echo "or run $0 accept-eula"
+	exit 1
+  fi
+	
 }
 	
+#
+# prepare console files
+#
+
+ResetConsoleFiles() {
+
+	rm -f $MC_DIR/input.con
+	rm -f $MC_DIR/output.con
+	
+	if [ -f $MC_DIR/input.con ]; then
+		echo "$MC_DIR/input.con could not be removed"
+		exit 1
+	fi
+
+       	if [ -f $MC_DIR/output.con ]; then
+                echo "$MC_DIR/output.con could not be removed"
+                exit 1
+        fi
+
+	execCMD "touch $MC_DIR/input.con"
+	execCMD "touch $MC_DIR/output.con"
+
+	if [ ! -f $MC_DIR/input.con ]; then
+		echo "$MC_DIR/input.con could not be created by $MC_USER"
+		exit 1
+	fi
+
+        if [ ! -f $MC_DIR/output.con ]; then
+                echo "$MC_DIR/output.con could not be created by $MC_USER"
+                exit 1
+        fi
+
+}
+
+
 #
 # start the minecraft server
 #
 
 start() {
    echo -n "Starting minecraft server as user $MC_USER..."
+
    checkOK 
 
-   echo
+   ResetConsoleFiles
+
+
+   # be in right working directory when starting 
+   cd $MC_DIR
+
+   execCMD "tail -f --pid=\$$ $MC_DIR/input.con | { $JAVACMD $MC_JAVA_OPS -jar $MC_DIR/minecraft.jar nogui > $MC_DIR/output.con 2>&1 ; kill \$$ ; } " &
+
+   # check if the command wait OK
+
+   if [ $? -ne 0 ]; then
+     echo "Could not start $MC_DIR/minecraft.jar.\n"
+     exit 1
+   fi
+
+   # wait 2 seconds to see if the process survived
+
+   sleep 2
+
+   if [ $(isRunning) -eq 1 ] ; then
+     echo "Started"
+   else
+     echo "stopped again"
+     exit 1
+   fi
+
+}
+
+stop() {
+  local i
+
+  echo -n "Stopping minecraft server..."
+
+  sendCMD "stop"
+
+  # wait for 10 seconds until killing it
+  i=0
+
+  while [ $i -lt 10  -a $(isRunning) -eq 1 ]
+  do
+    echo -n "."
+    sleep 1
+    i=`expr $i + 1`
+  done
+
+  if [ $(isRunning) -eq 1 ] ; then
+     echo -n  "(need to kill it)..."
+     kill  $(getPID)
+     # give it time to die
+     sleep 2
+  fi
+
+  if [ $(isRunning) -eq 1 ] ; then
+     echo "Could not stop it"
+     exit 1
+  else
+     echo "Stopped" 
+  fi
+
+}
+seteula() {
+    
+    # make sure that we have an eula.txt file to modifie
+
+    createEULA
+
+    setProp $MC_DIR/eula.txt "eula" "true"
+
+    echo "EULA accepted"
+
 }
 
 case "$1" in
@@ -131,7 +303,11 @@ case "$1" in
   ;;
 
   stop)
-
+    if [ $(isRunning) -eq 1 ] ; then
+       stop
+    else
+      echo "$MC_PROC is not running" 
+    fi
   ;;
 
   restart)
@@ -145,9 +321,20 @@ case "$1" in
   ;;
 
   status)
+    if [ $(isRunning) -eq 1 ] ; then
+        echo -n "$MC_PROC is running with PID "
+        getPID
+    else
+	echo "$MC_PROC is not running"
+    fi
 
   ;;
 
+  accept-eula)
+
+    seteula
+
+  ;;
   send)
 
   ;;
